### ISSUE TITLE
AngularJS rebind action on every ons-navigator.bringPageTop

### ISSUE THREAD

**Issue by khuongcomputer** [OnsenUI/OnsenUI#1324]
Each time ons-navigator.bringPageTop is fired, DOM reloaded and angularJS add ng-click, ng-repeat... on that page and cause ng-click happen multiple times.

`(function() {
	  var myApp = angular.module('app',['onsen']);  
	  myApp.controller('mainController', function($scope) {
		  this.test = function(){
			  alert('test');
		  }.bind(this);
	  });
	})();`

`<ons-navigator var="mainNav" page="page1.html"></ons-navigator>
	
	<ons-template id="page1.html">
		<ons-page ng-controller="mainController">
			<span ng-click="mainNav.bringPageTop('page2.html')">content here</span>
		</ons-page>
	</ons-template>
	<ons-template id="page2.html">
		<ons-page ng-controller="mainController as ctl">
			<span ng-click="mainNav.bringPageTop('page1.html')">content here - page 2</span>
			<span ng-click="ctl.test()">test click here</span>
		</ons-page>
	</ons-template>`

To replicate issue, click on content here to switch between pages several times and click on test click, it will alert several times. Only once alert expected.

**Comment by IliaSky** [comment]
The fix has been merged, so I'm closing this issue.

**Comment by khuongcomputer** [comment]
Data still getting rebind, and if I put ng-click="console.log(data1); console.log(data2)" it'll output data2 x times the page is loaded.

**Comment by IliaSky** [comment]
Are you sure that you are using beta 9?
Anyway the update which you are giving is strange - it bugs only on the second part?
[Here's a codepen](http://codepen.io/IliaSky/pen/NNabXw?editors=1000) with the problem you are describing, but I don't see the behaviour which you're talking about. Please modify it so that we can see the issue, because currently we're unable to reproduce it.
