### ISSUE TITLE
ons-bottom-toolbar data-binding issue in Google Chrome

### ISSUE THREAD

**Issue by MortezaT** [OnsenUI/OnsenUI#1426]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environments__

    Onsen 2 RC 5
    Angular 1.5.5
    Android 5.0.0
=====
    Ubuntu 16.0.4 LTS
    Chromium 50
-----
__Encountered problem__
OnsenUI 2 TypeError on `ons-bottom-toolbar`

__How to reproduce__
As subscribed [here][1] there is a problem with bottom toolbar in Chrome browser with these errors:

    TypeError: Cannot read property 'childNodes' of undefined
    TypeError: Cannot set property 'nodeValue' of undefined

[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)
[1]: http://stackoverflow.com/questions/37363975/onsen-ui-2-rc5-ons-bottom-toolbar-angular-template-typeerror-cannot-set-prope

**Comment by argelius** [comment]
@MortezaT Thank you for reporting!

Can you add some more info on how to reproduce this? I tried it in Chrome 50 without any problem.

Can you paste the whole `index.html` that triggers this error?

**Comment by vjoomens** [comment]
Hi, same issue here. Try this:

`<ons-navigator animation="slide" var="nav" id="navigator" page="profiles.html">
    <ons-page>
        <ons-sliding-menu main-page="profiles.html" menu-page="menu.html" side="left" max-slide-distance="250px" var="menu">
        </ons-sliding-menu>
    </ons-page>
</ons-navigator>`

**Comment by MortezaT** [comment]
@argelius 
Here is what I do:
This is the structure:
```
app
-- js
  -- app.js
-- templates
  -- main.html
  -- menu.html
-- vendor
  -- onsenui
      .
      .
  -- angular
      .
      .
index.html
```
#### Index.html
```
<!DOCTYPE html>
<html ng-cloak ng-controller="MainCtrl">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>{{ appName }}</title>
		<link rel="stylesheet" href="./vendor/angular/angular-csp.css">
		<link rel="stylesheet" href="./vendor/onsenui/css/onsenui.css">
		<link rel="stylesheet" href="./vendor/onsenui/css/onsen-css-components.css">
		<link rel="stylesheet" href="./vendor/onsenui/css/onsen-css-components-blue-theme.css">

	</head>
	<body>

		<ons-sliding-menu id="sliding-menu" var="app.menu" main-page="templates/main.html" menu-page="templates/menu.html" type="push" direction="right" max-slide-distance="18em"></ons-sliding-menu>

		<script src="vendor/angular/angular.js"></script>
		<script src="vendor/onsenui/js/onsenui.js"></script>
		<script src="vendor/onsenui/js/angular-onsenui.js"></script>

		<script src="js/app.js"></script>
	</body>
</html>
```
#### main.html
```
<ons-page>
	<ons-toolbar>
		<ons-toolbar-button
			class="left"
			ng-click="app.menu.toggleMenu()">
			<ons-icon icon="ion-navicon"></ons-icon>
		</ons-toolbar-button>
		<div class="center">Main Page</div>
	</ons-toolbar>
	<ons-bottom-toolbar>
		<ons-row class="bottom-bar__line-height">
			<ons-col width="2%"></ons-col>
			<ons-col width="10%"></ons-col>
			<ons-col width="2%"></ons-col>
			<ons-col width="72%">{{ test }}</ons-col>
			<ons-col width="2%"></ons-col>
			<ons-col width="10%">
				{{ 'this is a test' }}
			</ons-col>
			<ons-col width="2%"></ons-col>
		</ons-row>
	</ons-bottom-toolbar>
</ons-page>
```
#### menu.html
```
<div>
	This is the menu.
</div>
```

#### app.js
```
(function () {
	var app = ons.bootstrap('issue')
		.controller('MainCtrl', ['$scope',
			function ($scope) {
				$scope.appName = 'issue';
				$scope.test = 'this is another test';
			}
		]);
})();
```

**Comment by argelius** [comment]
Thanks a lot @MortezaT and @vjoomens !

Your samples were very helpful. This has been fixed now and will work in the next version.

**Comment by MortezaT** [comment]
@argelius Thank you but the problem is still there.
check this [fiddle][1].
[1]:https://jsfiddle.net/a3t3j0oz/

**Comment by argelius** [comment]
@MortezaT It has been fixed but not released yet. It will be released next week.

**Comment by madagon** [comment]
Hello guys!
Problem reappeared after ver 2 release.
