### ISSUE TITLE
ons-list.refresh() doesn't work/exist in Onsen2

### ISSUE THREAD

**Issue by erikcw** [OnsenUI/OnsenUI#1523]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 git master
Angular 1.5.7
Chrome/OSX

__Encountered problem__

I'm try to call the `refresh()` method of an ons-list (with ons-lazy-repeat) -- but the method doesn't exist.

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

```html
            <ons-list id="everyonePostsList" ng-controller="EveryoneController">
                <ons-list-item ons-lazy-repeat="InfitiniteScrollDelegate">
                    <div class="post">{{ item }}
                    </div>
               </ons-list-item>
           </ons-list>
```

```js
document.getElementById("everyonePostsList").refresh()
// VM32827:1 Uncaught TypeError: document.getElementById(...).refresh is not a function(…)
```

**Comment by argelius** [comment]
@erikcw Thanks!

I have fixed this. However, for the AngularJS directive the `refresh()` method is exposed in a slightly different way since we are not using the `<ons-lazy-repeat>` element.

The `refresh()` method is attached to the delegate object dynamically so you can do something like:

```
$scope.InfiniteScrollDelegate.refresh();
```

This will be available in the next release.

**Comment by erikcw** [comment]
@argelius So I tried accessing `refresh()` from the delegate object, and I still get an error saying 

```js
(index):223 TypeError: $scope.InfitiniteScrollDelegate.refresh is not a function
    at EveryoneCtrl.js:74
    at processQueue (angular.js:16170)
    at angular.js:16186
    at Scope.$eval (angular.js:17444)
    at Scope.$digest (angular.js:17257)
    at Scope.$apply (angular.js:17552)
    at done (angular.js:11697)
    at completeRequest (angular.js:11903)
    at XMLHttpRequest.requestLoaded (angular.js:11836)
```

I'm on Onsen 2.0.0-rc.17.

**Comment by erikcw** [comment]
For reference...

```html
<ons-list id="everyonePostsList" var="everyonePostsList" ng-controller="EveryoneController" ng-if="posts.length">
  <ons-list-item ons-lazy-repeat="InfitiniteScrollDelegate">
    ...
  </ons-list-item>
</ons-list>
```
