### ISSUE TITLE
App broken rc18 ->

### ISSUE THREAD

**Issue by vjoomens** [OnsenUI/OnsenUI#1588]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 rc 17
Angular 1.5.8
Any platform

__Encountered problem__
After updating to onsen ui 2.0.0-rc18 or later my application is broken and shows the following error. rc17 works fine. Please help, because I would like to update to prod version 2.

![2016-09-16_1138](https://cloud.githubusercontent.com/assets/4560105/18581740/2e646c5e-7c02-11e6-81eb-23dcccfe9c6c.png)

**Comment by argelius** [comment]
@vjoomens Does this happen in split view or sliding menu?

**Comment by vjoomens** [comment]
This happens with the sliding menu. Here's an example.

```
<ons-navigator animation="slide" var="nav" id="navigator">
    <ons-page>
        <ons-sliding-menu main-page="profiles.html" menu-page="menu.html" side="left" max-slide-distance="250px"
                          var="menu" id="mainMenu">
        </ons-sliding-menu>
    </ons-page>
</ons-navigator>

<ons-template id="menu.html">
    <ons-page class="regular-background">
        <ons-toolbar modifier="main-toolbar"></ons-toolbar>
        <ons-list class="menu-list">
            <ons-list-item modifier="chevron" onclick="menu.setMainPage('profiles.html', {closeMenu: true})">
                {{ 'common.messages' | i18n }}
            </ons-list-item>
        </ons-list>
    </ons-page>
</ons-template>

<ons-template id="profiles.html">
    <ons-page ng-controller="ProfilesController" class="white-background">

    </ons-page>
</ons-template>
```

**Comment by argelius** [comment]
@vjoomens I think I figured out what's happening. Will fix later. On my phone now so I can't write code

**Comment by vjoomens** [comment]
@argelius, did you find anything yet?

**Comment by argelius** [comment]
@vjoomens Sorry for the delay. I had a high fever so I was out of action for a few days. This has been resolved now and should work in the next version.

**Comment by vjoomens** [comment]
Thank you!

**Comment by vjoomens** [comment]
@argelius I just updated my project to use onsen ui 2.0.1, but it's still not working with RC18 or higher.
![2016-10-14_1416](https://cloud.githubusercontent.com/assets/4560105/19387176/cd7c2da0-9218-11e6-8d30-562923cf5098.png)
