### ISSUE TITLE
ons-tab duplicated when I use setActiveTab

### ISSUE THREAD

**Issue by jakwarrior** [OnsenUI/OnsenUI#1593]
**Environment**
Onsen 2.0.0
Angular 1.5.5
Chrome 53

**Encountered problem**
When I use the method setActiveTab(i), the ons-tab number i is duplicated.
Maybe it's related to issue #1584 but it's not exactly the same issue.

**How to reproduce**
I create an example : [codepen](https://codepen.io/anon/pen/gwwxPm)
There is two tabs. It works well without the "setActiveTab" method. But when I use it, I can see there is two "tab2", and the "postchange" event fire twice : 
![error1](https://cloud.githubusercontent.com/assets/11635390/18630835/12d2f7c0-7e6f-11e6-8417-3c7666df397c.png)
![error2](https://cloud.githubusercontent.com/assets/11635390/18630838/1765c22c-7e6f-11e6-8c09-f819b9867f90.png)

**Comment by FruityXXL** [comment]
I've exactly the same probem! 

Onsen 2.0.0
Onsen 2.0.1
Pure JS

Is there a bugfix in sight? Thanks!

**Comment by argelius** [comment]
@jakwarrior @FruityXXL I will take a look at this issue. Sorry for the delay.

**Comment by argelius** [comment]
Sorry for the delay. This issue has been resolved now.

**Comment by jakwarrior** [comment]
There is still an issue. The tab is not duplicated but the method setActiveTab(i) doesn't work. I updated my example with Onsen 2.0.4 : [codepen](https://codepen.io/anon/pen/gwwxPm)
In this example, it's "Tab 1" which is displayed instead of "Tab 2".

**Comment by angelcasellas** [comment]
Hi @argelius. In a page when I use tabbar, sometimes in the pageinit event I do not still have the template loaded and so I can't put content into the page__content div that onsen generate automatically. How can I manage to make sure that the div has already been loaded instead of using pageinit event?

Thanks in advance!

**Comment by munsterlander** [comment]
@jakwarrior When I view your codepen, it shows it is still using 2.0.0.  If it was updated to 2.0.4, that may resolve your issue.

@angelcasellas I use the `show ` event.  That way you know it has been loaded.
