### ISSUE TITLE
blank page at init with ons-splitter + ons-navigator

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1623]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

**Environment**
Onsen 2.0.1
Angular 1.5.8

**Encountered problem**

Hi, 

I have some errors at init, and I was waiting for v2.0 to see if it still happens.
In v2.0.1, it is:
- a blank page at init with ons-splitter + ons-navigator.
- 2 js errors
### Blank page error

splitter page not displayed at init, due to _style="display: none;"_ 
- html code

```
<ons-navigator var="onsNavigator" page="splitter.html"></ons-navigator>

<ons-template id="splitter.html">
<ons-page id="splitter-page">
<ons-splitter id="mainSplitter" >
    <ons-splitter-side var="menu" side="left"
        width="80%" collapse swipeable page="menu.html">
    </ons-splitter-side>

    <ons-splitter-content page="main.html"></ons-splitter-content>
</ons-splitter>
</ons-page>
</ons-template> 
```
- generated code

```
<ons-page id="splitter-page" class="page ng-scope" name="splitter.html" style="display: none;">
<div class="page__background"></div>
<div class="page__content">
<ons-splitter id="mainSplitter" class="ng-scope" data-device-back-button-handler-id="2">
<ons-splitter-side var="menu" side="left" width="80%" collapse="" swipeable="" page="menu.html" mode="collapse" style="width: 80%; transform: translate3d(0px, 0px, 0px);">
<ons-page id="menu-page" class="page ng-scope">
</ons-splitter-side>
<ons-splitter-content page="main.html" style="left: 0px;">
<ons-page id="main-page" class="page ng-scope" ng-controller="MainController" ...
```
### Solution to bypass blank page

```
ons.ready(function() {
         $('#splitter-page').show();
    });
```
###  Js errors

**TypeError: view is undefined**
- in angular-onsenui.js v2.0.1 (ligne 11035, col. 7)

```
  window.ons.SplitterContentElement.rewritables.link = function (element, target, options, callback) {
    var view = angular.element(element).data('ons-splitter-content');......................................... view is null
    lastLink(element, target, options, function (target) {
      view._link(target, callback);
    });
  };
```
- in angular-onsenui.js v2.0.1 (ligne 8473, col. 5)

```
  window.ons.NavigatorElement.rewritables.link = function (navigatorElement, target, options, callback) {
    var view = angular.element(navigatorElement).data('ons-navigator');......................................... view is null
    view._compileAndLink(target, function (target) {
      lastLink(navigatorElement, target, options, callback);
    });
  };
```

Regards,
Benjamin

**Comment by argelius** [comment]
@bdedardel I am unable to reproduce this error (blank page). Can you create a Codepen example where it fails?

The error message is due to the content of the template being compiled by Angular. We will try to fix this error message.

**Comment by bdedardel** [comment]
Hi,

I've just committed an example in my github repo:

[bdedardel/cordova-test/tree/master/onsenui/bug1623](https://github.com/bdedardel/cordova-test/tree/master/onsenui/bug1623)

You should get these logs:

```
onsenui::init(): begin...
onsenui::init(): end!
I must still look at it => TypeError: this._backButtonHandler is undefined
[onsenuilog] OnsenUIStorage::init(LokiOnsenUIStorage)
[onsenuilog] OnsenUIStorage::init() load database
[onsenuilog] OnsenUIStorage::init() get 'mymodels' collection 
AppController::constructor(): begin...
AppController::constructor(): end!
[onsenuilog] Navigator::getCurrentPage - page[0] = splitter.html
[onsenuilog] Navigator::getCurrentPage - top page splitter.html
[onsenuilog] MyModelController#1::constructor(): page: splitter.html
[onsenuilog] OnsenUIStorage::getMyModelItems() => 3
[onsenuilog] ons.ready
[onsenuilog] pageinit: id='menu-page' pageinit

... and after some few seconds:
 
TypeError: view is undefined           angular...enui.js (ligne 11035, col. 7)
TypeError: view is undefined           angular...enui.js (ligne 8473, col. 5)
```

Regards,
Benjamin

**Comment by bdedardel** [comment]
Note: I've tested my solution on Linux / Firefox (my dev env).
I use chromium to debug my cordova app once it works fine on my pc.

**Comment by argelius** [comment]
@bdedardel I can still not reproduce this. I tried with both Chrome and Firefox.

Can you create a minimal example that reproduces this?

**Comment by bdedardel** [comment]
@argelius Hi, I've already created an example in:

https://github.com/bdedardel/cordova-test/tree/master/onsenui/bug1623

In js/main.js, if you comment : 

```
// $('#splitter-page').show();
```

you should have a blank page.

**Comment by argelius** [comment]
@bdedardel Is it possible to create a minimal example that reproduces this? This example contains a lot of code that I don't think is related to the issue.

**Comment by bdedardel** [comment]
@argelius Hi, I've updated my example in:

https://github.com/bdedardel/cordova-test/tree/master/onsenui/bug1623

In js/main.js, if you comment :

```
// $('#splitter-page').show();
```
blank page still appear for me with Linux Ubuntu / firefox

**Comment by bdedardel** [comment]
@argelius Hi, I made some new tests on initialization.
see: https://github.com/bdedardel/cordova-test/tree/master/onsenui/bug1623

No blank pages with chromium, but still some errors in logs.
Here are the results for firefox, without being able to analyse them without you!


Firefox - angular-onsenui before onsenui in head
--------------------------------------

### index.html

```
<head>
	...
	<script src="js/devDeps/angular.js"></script>
	<script src="js/devDeps/angular-onsenui.js"></script>
	<script src="js/devDeps/onsenui.js"></script>
	...
</head>
<body>
	...
	<script src="js/core.js"></script>
	<script src="js/main.js"></script>
</body>
```

### result

- No blank page
- There is an error: **TypeError: ons._readyLock is undefined**

```
angular-onsenui waitOnsenUILoad... 
TypeError: ons._readyLock is undefined angular...enui.js (ligne 118, col. 6)
core::init(): begin... 
core::init(): end! 
[main] ons.ready 
```

Firefox - angular-onsenui after onsenui in head
--------------------------------------

### index.html

```
<head>
	...
	<script src="js/devDeps/angular.js"></script>	
	<script src="js/devDeps/onsenui.js"></script>
	<script src="js/devDeps/angular-onsenui.js"></script>
	...
</head>
<body>
	...
	<script src="js/core.js"></script>
	<script src="js/main.js"></script>
</body>
```

### result

- No blank page
- There is an error: **TypeError: view is undefined** in js/devDeps/angular-onsenui.js (ligne 11061, col. 7) due to *angular.element(element).data('ons-splitter-content') is undefined* in js/devDeps/angular-onsenui.js (ligne 11056)

```
angular-onsenui waitOnsenUILoad... 
core::init(): begin... 
core::init(): end! 
angular-onsenui - window.ons.SplitterContentElement.rewritables.link angular.element(element) is ok: Object[ons-splitter-content] 
angular-onsenui - window.ons.SplitterContentElement.rewritables.link angular.element(element).data('ons-splitter-content') is NOK: undefined
[main] ons.ready 
angular-onsenui - window.ons.NavigatorElement.rewritables.link angular.element(navigatorElement) is ok
angular-onsenui - window.ons.NavigatorElement.rewritables.link angular.element(navigatorElement).data('ons-navigator') is ok
angular-onsenui - window.ons.SplitterContentElement.rewritables.link angular.element(element) is ok
angular-onsenui - window.ons.SplitterContentElement.rewritables.link angular.element(element).data('ons-splitter-content') is ok

some few seconds later:

TypeError: view is undefined angular...enui.js (ligne 11061, col. 7)
```

Firefox - angular-onsenui after onsenui in body
--------------------------------------

### index.html

```
<body>
	...
	<script src="js/devDeps/angular.js"></script>
	<script src="js/devDeps/angular-onsenui.js"></script>	
	<script src="js/devDeps/onsenui.js"></script>	
	<script src="js/core.js"></script>
	<script src="js/main.js"></script>
</body>
```

### result

- There is a **blank page**
- There is an error: **TypeError: view is undefined** in js/devDeps/angular-onsenui.js (ligne 8493, col. 2) due to *angular.element(navigatorElement).data('ons-navigator') undefined* in js/devDeps/angular-onsenui.js (ligne 8489)
- and another error: **TypeError: this._backButtonHandler is undefined** in onsenui.js (ligne 22337, col. 10)

**Note**:

*angular.element(element).data('ons-splitter-content')* is fine, after *ons.ready* call

```
angular-onsenui waitOnsenUILoad...
angular-onsenui - window.ons.NavigatorElement.rewritables.link angular.element(navigatorElement) is ok
angular-onsenui - window.ons.NavigatorElement.rewritables.link angular.element(navigatorElement).data('ons-navigator') is NOK: undefined
TypeError: this._backButtonHandler is undefined onsenui.js (ligne 22337, col. 10)
core::init(): begin...
core::init(): end!
[main] ons.ready
angular-onsenui - window.ons.SplitterContentElement.rewritables.link angular.element(element) is ok
angular-onsenui - window.ons.SplitterContentElement.rewritables.link angular.element(element).data('ons-splitter-content') is ok

and some few seconds later: 

TypeError: view is undefined angular...enui.js (ligne 8493, col. 2)
```

**Comment by misterjunio** [comment]
@bdedardel I tried your code with the latest Onsen UI releases and everything seems fine, no errors thrown from either navigator or splitter. You can just grab your `bug1623` code, remove the `body` scripts and add the following ones on the `head`:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/onsen/2.2.2/js/onsenui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/onsen/2.2.2/js/angular-onsenui.js"></script>
<script src="js/core.js"></script>
<script src="js/main.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/onsen/2.2.2/css/onsenui.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/onsen/2.2.2/css/onsen-css-components.css" />
```

They are the latest releases of Onsen UI and Angular 1.5.8. Everything should run smoothly.

**Comment by misterjunio** [comment]
@bdedardel I guess everything is fine now so I will close this issue 👍
