### ISSUE TITLE
Can not set width to `<ons-input>`.

### ISSUE THREAD

**Issue by cyciopes** [OnsenUI/OnsenUI#1974]
```
[Core]
    onsenui 2.2.5

[Framework]
    javascript core

[Framework binding]
    none

```

Can not set width to `<ons-input>`.
In ios view, no response.
In android view, it is not the expect result, especial underbar. 
I just add `style="width: 100%" `.
```
<ons-input id="username" modifier="underbar" placeholder="Username" style="width: 100%" ></ons-input>
```
![2017-04-25 15_37_15-ons-input](https://cloud.githubusercontent.com/assets/21193224/25373677/2a6a44e2-29cd-11e7-9df7-0b174fe8cf33.png)
![2017-04-25 15_40_52-ons-input](https://cloud.githubusercontent.com/assets/21193224/25373800/98e5f380-29cd-11e7-93b9-2b942af719cc.png)

**Comment by frandiox** [comment]
@cyciopes Thanks for reporting, I just fixed it :)

**Comment by ilmuwebsite** [comment]
@frandiox I've been trying to update it to  2.2.5 but still not working when i use

<ons-input id="username" modifier="underbar" placeholder="Username" style="width: 100%" ></ons-input>

how to change ons-input to full width ?

**Comment by asial-matagawa** [comment]
@ilmuwebsite 
It's already fixed but simply not yet released.
We are going to release `onsenui@2.2.6`, so please be patient for a while.

Or you can add this code into your stylesheet file to fix the problem:
```css
ons-input .text-input__container input {
    width: 100%;
    display: inline-block;
}
```

**Comment by ilmuwebsite** [comment]
oke thank a lot
