### ISSUE TITLE
Vue | Pull Hook issue: page content shaking vigorously while scrolling up or down in iOS WKWebView

### ISSUE THREAD

**Issue by ychongsaytc** [OnsenUI/OnsenUI#2429]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui latest

[Platform]
  Desktop - OS X 10.13.4 64-bit
  iOS 11.3.1

[Browser]
  Desktop - Chrome 66.0.3359.181 on OS X 10.13.4 64-bit
  WKWebView
```

__Encountered problem__
The whole page content keep shaking vigorously while scrolling up or down in iOS WKWebView

__How to reproduce__
Try to drag/scroll page content starts from (0, 0).

  
  [__Demo link (self-hosted)__](https://res.vales.io/20180517-ons-pull-hook/)
  [__Demo link (codepen)__](https://codepen.io/anon/pen/pVxYgM)
  [__Screen record video (self-hosted)__](https://res.vales.io/20180517-ons-pull-hook/index.mp4)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>

    <v-ons-toolbar>
      <div class="center">{{ title }}</div>
      <div class="right">
        <v-ons-toolbar-button>
          <v-ons-icon icon="ion-navicon, material: md-menu"></v-ons-icon>
        </v-ons-toolbar-button>
      </div>
    </v-ons-toolbar>

    <div class="content">

      <v-ons-pull-hook :action="action" :height="'40px'" @changestate="state = $event.state">
        <span v-show="state === 'initial'">
          pull to refresh
        </span>
        <span v-show="state === 'preaction'">
          release to refresh
        </span>
        <span v-show="state === 'action'">
          refreshing&hellip;
        </span>
      </v-ons-pull-hook>

      <p>Duris caelum tuti. Persidaque invasit regat. Dicere locoque iapeto colebat. Sublime tumescere inminet agitabilis tractu aequalis. Circumdare origine lanient circumdare. Scythiam fontes manebat hominum. Terrenae pinus membra meis iners. Primaque tollere campoque secuit illi aliud sectamque. Illi fuerant volucres mundi nulli frigida astra.</p>

      <p>Totidemque vindice uno pondere dissaepserat fratrum umentia mortales terris. Pace pendebat cingebant animalia omnia militis iners sponte emicuit. Ante terra terrae poena recessit locum duris iunctarum igni. Fossae habitabilis. Aliis colebat aer cuncta verba lege habendum tuba. Caeca occiduo terram locis et tractu.</p>

      <p>Terra duas. Addidit volucres quanto titan facientes zonae tepescunt solidumque? Aer sui. Terrenae ponderibus ulla vesper est naturae. Gentes frigore terras dispositam spisso quisque et bracchia eurus. Speciem glomeravit sed. Dominari fert grandia campoque bracchia praeter satus effervescere. Poena undas tempora faecis homo.</p>

      <p>Duris caelum tuti. Persidaque invasit regat. Dicere locoque iapeto colebat. Sublime tumescere inminet agitabilis tractu aequalis. Circumdare origine lanient circumdare. Scythiam fontes manebat hominum. Terrenae pinus membra meis iners. Primaque tollere campoque secuit illi aliud sectamque. Illi fuerant volucres mundi nulli frigida astra.</p>

      <p>Totidemque vindice uno pondere dissaepserat fratrum umentia mortales terris. Pace pendebat cingebant animalia omnia militis iners sponte emicuit. Ante terra terrae poena recessit locum duris iunctarum igni. Fossae habitabilis. Aliis colebat aer cuncta verba lege habendum tuba. Caeca occiduo terram locis et tractu.</p>

      <p>Terra duas. Addidit volucres quanto titan facientes zonae tepescunt solidumque? Aer sui. Terrenae ponderibus ulla vesper est naturae. Gentes frigore terras dispositam spisso quisque et bracchia eurus. Speciem glomeravit sed. Dominari fert grandia campoque bracchia praeter satus effervescere. Poena undas tempora faecis homo.</p>

      <p>Duris caelum tuti. Persidaque invasit regat. Dicere locoque iapeto colebat. Sublime tumescere inminet agitabilis tractu aequalis. Circumdare origine lanient circumdare. Scythiam fontes manebat hominum. Terrenae pinus membra meis iners. Primaque tollere campoque secuit illi aliud sectamque. Illi fuerant volucres mundi nulli frigida astra.</p>

      <p>Totidemque vindice uno pondere dissaepserat fratrum umentia mortales terris. Pace pendebat cingebant animalia omnia militis iners sponte emicuit. Ante terra terrae poena recessit locum duris iunctarum igni. Fossae habitabilis. Aliis colebat aer cuncta verba lege habendum tuba. Caeca occiduo terram locis et tractu.</p>

      <p>Terra duas. Addidit volucres quanto titan facientes zonae tepescunt solidumque? Aer sui. Terrenae ponderibus ulla vesper est naturae. Gentes frigore terras dispositam spisso quisque et bracchia eurus. Speciem glomeravit sed. Dominari fert grandia campoque bracchia praeter satus effervescere. Poena undas tempora faecis homo.</p>

    </div>

  </v-ons-page>
</template>

<div id="app"></div>

```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  data: function () {
    return {
      state: 'initial'
    };
  },
  methods: {
    action: function (done) {
      setTimeout(function () {
        done()
      }, 1e3)
    }
  }
})

```

**Comment by asialgearoid** [comment]
Thanks for the detailed report, @ychongsaytc. It looks like Fran fixed this in [this commit](https://github.com/OnsenUI/OnsenUI/commit/62c22f22d06e6658f926b7cd873a34216a0b467a). We have just released onsenui@2.10.0, which includes this fix. Could you test with 2.10.0 and see if the issue is fixed?

**Comment by ychongsaytc** [comment]
But the issue still exists in the latest version of OnsenUI. @asialgearoid 

- [Demo (self-hosted)](https://res.vales.io/20180517-ons-pull-hook/)
- [Screen record video (self-hosted)](https://res.vales.io/20180517-ons-pull-hook/index.mp4)

```html
<script type="text/javascript" src="https://unpkg.com/onsenui/js/onsenui.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script type="text/javascript" src="https://unpkg.com/vue-onsenui/dist/vue-onsenui.js"></script>
<link rel="stylesheet" media="all" href="https://unpkg.com/onsenui/css/onsenui.css" />
<link rel="stylesheet" media="all" href="https://unpkg.com/onsenui/css/onsen-css-components.css" />
```

```html
/* onsenui v2.10.0 - 2018-05-17 */
```

```html
/*!
 * Vue.js v2.5.16
 * (c) 2014-2018 Evan You
 * Released under the MIT License.
 */
```

```html
/* vue-onsenui v2.6.0 - 2018-05-17 */
```

**Comment by asialgearoid** [comment]
@ychongsaytc Thanks for confirming you are still having the issue, and for your detailed report. However, I an unable to reproduce the scrolling issues you show in your video.

I tested your code on an iPhone X (iOS 11.3) in both Safari and a Cordova app with `cordova-plugin-wkwebview-engine`. The scrolling is fine after pulling to refresh, even close to the top.

Could you detail exactly how to reproduce the problem?

**Comment by ychongsaytc** [comment]
@asialgearoid  Thanks, the problem was resolved.

I found the problem in `ons-pull-hook.js`. The page shaking while the `_shouldFixScroll` is `true`.

This problem occurs when iOS WKWebView is initialized without `addScriptMessageHandler()` or is not based on Cordova framework. Then `window.webkit` and `window.webkit.messageHandlers` are both `undefined`.

Anyway, thanks for you helps!

**Comment by asialgearoid** [comment]
@ychongsaytc Thanks for the explanation, I'm glad you managed to fix your issue.
