### ISSUE TITLE
Ons-tabbar loadPage() function doesn't destroy previous page

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#751]
The page stack increase every time the function has been called, it should not be default behavior.

**Comment by andipavllo** [comment]
@argelius I fixed this and made a pull request

**Comment by Mi5i** [comment]
This issue is still in version 1.3x. I almost pulled all my hair when I realised that.
I could fix it with your solution here. Please put it in 1.3x. Thank you.

**Comment by frankdiox** [comment]
@Mi5i Oh! Looks like we forgot to added to Onsen 1. Thanks for reporting!

@andipavllo  Can you fix this?

**Comment by andipavllo** [comment]
yes, I will check this
